# -*- coding: utf-8 -*-
"""DL-Uygulama.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V-rUb7WCokDH7VfrfCj9vRSQhIZUoS6w

## Stil Transferi

### Kütüphanelerin Yüklenmesi
"""

import tensorflow as tf
import tensorflow_hub as hub

from PIL import Image
import numpy as np

"""### Modelin Yüklenmesi ve Fonksiyonların Tanımlanması"""

model = hub.load("https://tfhub.dev/google/magenta/arbitrary-image-stylization-v1-256/2")

def load_image(image_path, max_dim):
  img = Image.open(image_path).convert('RGB')
  img.thumbnail((max_dim, max_dim))
  arr = np.array(img)/255.0
  return tf.expand_dims(arr.astype(np.float32), axis=0)

def stylize(content_path, style_path, content_max=512, style_max=256):
  content = load_image(content_path, content_max)
  style = load_image(style_path, style_max)
  outputs = model(tf.constant(content), tf.constant(style))
  stylized = outputs[0][0].numpy()
  stylized = (stylized*255).clip(0,255).astype(np.uint8)
  return Image.fromarray(stylized)

"""### Dosyaların Yüklenmesi"""

from google.colab import files

print('İçerik görsellerini yükleyin😊 ')
uploaded = files.upload()
content_path = list(uploaded.keys())[0]

print('Stil dosyanızı yükleyin😊 ')
uploaded = files.upload()
style_path = list(uploaded.keys())[0]

"""### Stil Transferinin Yapılması"""

import matplotlib.pyplot as plt

result = stylize(content_path, style_path)
plt.imshow(result)

"""### Kaydetme İşlemleri"""

result.save('result.jpg')

files.download('result.jpg')